spring:
  application:
    name: academic-authentication
  config:
    import: optional:configserver:https://root:4c4d3mIc5ec12eT@guidance-config-service.herokuapp.com
  cloud:
    config:
      uri: https://guidance-config-service.herokuapp.com/
      discovery:
        enabled: true
        service-id: CONFIG-SERVICE
      retry:
        initial-interval: 2000
        multiplier: 1.5
        max-interval: 60000
        max-attempts: 100
      profile: development
      username: root
      password: 4c4d3mIc5ec12eT
      label: main
      name: academic-authentication-service

eureka:
  instance:
    hostname: academic-authentication-service.herokuapp.com
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: https://guidance-discovery-service.herokuapp.com/eureka/